#!/bin/bash

DEBUG=1;

function adDebug {
     if [ $DEBUG -gt 0 ]
     then
        cat >> /tmp/.advisor.debug
     else
        cat >> /dev/null
     fi

}

function altName {


     lsusb|grep "$*" |cut -f3 -d":"|cut -f2- -d" "

}


if [ -z "$DEVICE" ]
then
  echo "no device"
  exit 0
else
  LOCKFILE=/tmp/.$(echo $DEVICE|sed s/"\/"/"#"/g)
  if [ -f $LOCKFILE ]
     then 
        echo "Locked"
	exit 0;
     else
        touch $LOCKFILE
  fi   
  if [ -f  /tmp/.advisor.debug ]
  then
     rm /tmp/.advisor.debug
  fi
  #lockfile -r-1 -s1 $LOCKFILE
  #aplay  /usr/share/sounds/KDE_Window_Open.wav
  #SUBSYSTEM=usb
  #DEVPATH=/devices/pci0000:00/0000:00:03.0/usb2/2-1
  #MODALIAS=usb:v0E8Fp0003d0107dc00dsc00dp00ic03isc00ip00
  #DEVICE=/proc/bus/usb/002/027
  #PRODUCT=e8f/3/107
  VEID=$(echo $PRODUCT|cut -f1 -d"/")
  PRID=$(echo $PRODUCT|cut -f2 -d"/")
 
  TOTAL=$(wc -l /proc/bus/usb/devices|cut -f1 -d" ")
  MARK=$(cat /proc/bus/usb/devices|grep -n . |sed s/"^ \+"/""/g|grep $VEID|grep $PRID|cut -f1 -d":")
  NEXT=$(tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices|grep -m1 -n "Bus="|cut -f1 -d":")
  #set |adDebug 
  #env |adDebug
  
  echo "Debug" $VEID $PRID $TOTAL $MARK $NEXT | adDebug
  
  
  if [ -z "$NEXT" ]
  then
     #Last one
     tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices > $LOCKFILE
     echo "Running: tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices " |adDebug
  
  else
     tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices|head -$(( $NEXT-1 )) > $LOCKFILE
     echo "Running: tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices|head -$(( $NEXT-1 ))" |adDebug
  fi
  
  
  cat $LOCKFILE | adDebug
  
  FULLINFO=$(cat $LOCKFILE |grep -A5 "$VEID.\+$PRID")
  GDRIVER=$(cat $LOCKFILE |grep -A30 "$VEID.\+$PRID"|grep Driver|sed s/".\+Driver="/""/|uniq|sed s/" \+"/" "/g|sort)  
  SYSDEV=/sys/bus/usb/devices/$(echo $DEVPATH|cut -f5,6 -d "/")
  APRODUCT=$(cat $SYSDEV/product)
  AMANF=$(cat  $SYSDEV/manufacturer)
  ALTNAME=$(lsusb|grep "$VEID.\+$PRID" |cut -f3 -d":"|cut -f2- -d" ")
  if [ -z "$APRODUCT" ];then APRODUCT=$(altName "$VEID.\+$PRID");fi
    
  echo "Guessed driver: " $GDRIVER | adDebug
  echo "NEWPLUG: $PRODUCT $VEID/$PRID $APRODUCT ($AMANF) driver:'$GDRIVER' x '$DRIVER'"|sed s/" \+"/" "/g|logger
  #echo -e "\E[32;40;1m\033[1m"$FULLINFO|logger
      
  if [ "$GDRIVER" = "(none)" ]
  then
     #Maybe must wait for module to load
     sleep 5;
     TOTAL=$(wc -l /proc/bus/usb/devices|cut -f1 -d" ")
     MARK=$(cat -n /proc/bus/usb/devices |sed s/"^ \+"/""/g|grep $VEID|grep $PRID|cut -f1)
     NEXT=$(tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices|grep -m1 -n "Bus="|cut -f1 -d":")
  
     echo "Debug" $VEID $PRID $TOTAL $MARK $NEXT | adDebug
     if [ -z "$NEXT" ]
       then
     #Last one
       tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices > $LOCKFILE
       echo "Running: tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices"|adDebug
     else
       tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices|head -$(( $NEXT-1 )) > $LOCKFILE
       echo "Running: tail -n$(( $TOTAL-$MARK+1 )) /proc/bus/usb/devices|head -$(( $NEXT-1 ))"|adDebug
     fi
     cat $LOCKFILE|aDebug 
     GDRIVER=$(cat $LOCKFILE |grep -A30 "$VEID.\+$PRID"|grep Driver|sed s/".\+Driver="/""/|uniq|sed s/" \+"/" "/g|sort)  
     
     ADRIVER=$GDRIVER
     if [ -z "$APRODUCT" ];then APRODUCT=$(altName "$VEID.\+$PRID");fi
     
     echo "NEWPLUGx2: $VEID/$PRID $APRODUCT ($AMANF) driver:'$GDRIVER' x '$DRIVER'"|sed s/" \+"/" "/g|logger
  fi
  echo "lsusb|grep \"$VEID.\+$PRID\" |cut -f3 -d\":\"|cut -f2- -d\" \")"|adDebug
  RVI=$(cat /proc/bus/usb/devices |grep "$VEID.\+$PRID"|cut -f2 -d"="|cut -f1 -d" ")
  RPI=$(cat /proc/bus/usb/devices |grep "$VEID.\+$PRID"|cut -f3 -d"="|cut -f1 -d" ")
  
#  CUSERS=$(who|cut -f2|sed s/" \+"/" "/g |cut -f1,2 -d" "|grep ":[0-1]"|cut -f1 -d" ")
# Ubuntu doesn't report users on X
 CUSERS=$(find  /tmp/ksocket-* -name "kdeinit-:*"|cut -f2 -d"-"|cut -f1 -d"/")


  for i in $CUSERS
  do

       #UDISPLAY=$(who|cut -f2|sed s/" \+"/" "/g |cut -f1,2 -d" "|grep ":[0-1]"|grep $i|cut -f2 -d" ")
       UDISPLAY=$(find  /tmp/ksocket-* -name "kdeinit-:*"|grep $i|cut -f2 -d":")
       su $i -c "DISPLAY=:$UDISPLAY dcop khusba serviceInterface MyNotify \"<font size=\"+1\"><b>$APRODUCT</b> <br>($AMANF)</font><br>Controlador(es):<b>$GDRIVER</b>\" \"${RVI}${RPI}\""
  done
  rm $LOCKFILE

  # Now, let's update the database (in the background)
  (
  if [ -z "$ALTNAME" ];then sleep 5;ALTNAME=$(altName "$VEID.\+$PRID");lsusb|adDebug;fi
  mkdir -p /var/cache/khusba
  FILE=/var/cache/khusba/${RVI}${RPI}
  echo "DATA=" > $FILE
  echo "vendorxproduct=${RVI}:${RPI}" >> $FILE
  echo "description=$APRODUCT($AMANF)" >> $FILE
  echo "altdescription=$ALTNAME" >> $FILE
  echo "bus=USB" >> $FILE
  C=1;
  for i in $GDRIVER
  do
      echo "driver$C=$i" >> $FILE
      echo "driver${C}_version="$(modinfo $i|grep vermagic|cut -f2 -d":"|sed s/"^ \+"/""/) >> $FILE
      C=$(( $C+1 ))
  done
  SYSTEM=$(for i in $(ls /etc/*_version); do (echo $(echo $i|cut -f1 -d"_"|cut -f3 -d"/"):$(cat $i))2>/dev/null; done)
  if [ -f /etc/lsb-release ];then . /etc/lsb-release;fi
  SYSTEM="$SYSTEM $DISTRIB_DESCRIPTION $DISTRIB_CODENAME"
  echo "system="$SYSTEM >> $FILE
  echo "sfamily="$(uname -s -r -v  -m -p -i -o) >> $FILE
  echo "kversion="$(uname -r) >> $FILE
  shash=$(md5sum $FILE|cut -f1 -d" ")
  echo "shash=$shash" >> $FILE
  )&
fi
