Document: khusba
Title: Debian khusba Manual
Author: <insert document author here>
Abstract: This manual describes what khusba is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/khusba/khusba.sgml.gz

Format: postscript
Files: /usr/share/doc/khusba/khusba.ps.gz

Format: text
Files: /usr/share/doc/khusba/khusba.text.gz

Format: HTML
Index: /usr/share/doc/khusba/html/index.html
Files: /usr/share/doc/khusba/html/*.html

  
